function whatisit(){
    document.getElementById("h1titolo").innerHTML="WHAT IS IT?"
    document.getElementById("info").innerHTML="It is a goal \n setted by the UN, which has to improve the way we produce and consume.\n We have to do that because the economic and social progress over the last century has been accompanied by environmental degradation that is destroying our future development, Nowadays the amount of waste we are producing is incredible, the main things that we are wasting are - Raw materials such as water, food etc.. Only the 3% of all the water in the earth is dinkable, and everyday we are wasting more and more of this essential resource and the biggest problem with it is that we are not only wasting it but humankind is pollutioning waters and rivers faster than the nature can purifyAnother scary fact about the simple H2O is that it is not accesible by all human beings in the world, milions of people still do not have any access to it.The same is about the food, food industries are wasting it while there is a huge percent of humans that are starving - Energetic resourcesThe way we are producing electrical power is generating a lot of energetic waste and pollution. So we have to change the way we are producing one of the essential bricks in the human society, there are many ways we can product green electical power which has less or any emissions- Industial scraps The industial scraps of many insutrials sectors are generating an unmanagable pollution which will cause serious problems in the future -Domestic waste  Domestic wastes also matters, the way we are consuming is at the bottom of this pyramidal system, if we do not need much we will not get more So if we have to give a simple definition to sustainable production and consumption it will be about doing more and better with less. But it is not only that, it also about decoupling economic growth from environmental degradation, increasing resource efficiency and promoting sustainable lifestyles,it can also contribute substantially to poverty alleviation and the transition towards low-carbon and green economies"
}
function whicharethemaint(){
    document.getElementById("h1titolo").innerHTML="WHICH ARE THE MAIN TARGETS?"
    document.getElementById("info").innerHTML="There are 8 main targets that can create action for responsible consumption and production  \n 1 Implement the 10-year framework of programmes on sustainable consumption and production taking into account the development and capabilities of developing countries 2 Achieve the sustainable management and efficient use of natural resources 3 Halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains, including post-harvest losses 4 Achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, reduce their release to air, water and soil in order to minimize their adverse impacts on human health and the environment 5 reduce waste generation through prevention, reduction, recycling and reuse 6 Encourage companies to adopt sustainable practices and to integrate sustainability information into their reporting cycle  7 Promote public procurement practices that are sustainable, in accordance with national policies and priorities 8 ensure that people everywhere have the relevant information and awareness for sustainable development and lifestyles in harmony with nature"
}

function whyitmatters(){
    document.getElementById("h1titolo").innerHTML="WHY IT MATTERS SO MUCH?"
    document.getElementById("info").innerHTML="Economic and social progress over the last century has been accompanied by environmental degradation that is endangering the very systems on which our future development and very survival depend There are many aspects of consumption that with simple changes can have a big impact on society as a whole. \n For example, the global material footprint – an indicator of the pressure put on the environment to support economic growth and to satisfy the material needs of people – grew by 17.4 per cent to 85.9 billion metric tons in 2017 as compared to 2010. Reducing food loss and waste can contribute to environmental sustainability by lowering production costs and increasing the efficiency of food systems. Currently, we lose 13.8 % after harvesting and during transport, storage and processing alone, amounting to a cost of over $400 billion a year"
}

function whatcanwedo(){
    document.getElementById("h1titolo").innerHTML="WHAT CAN WE DO?"
    document.getElementById("info").innerHTML="Every positive action you take, no matter how small, has the power to make a difference. Supporting a clean the oceans campaign, switching to greener products, standing up for justice, and reminding your leaders of the promise of the Global Goals are all good places to start"
}


